### ISSUE TITLE
Feature: Built-in Music Player

### ISSUE THREAD

**Issue by Megami-Studios** [aMytho/GlimBoi#12]
One of the things I liked from another bot, Nightbot, is the built-in music player, which let me play my own music (or Soundcloud or YT tracks) instead of just relying on a streaming service like Pretzel or Soundtrack for Twitch.
![image](https://user-images.githubusercontent.com/2568634/109579632-446ce580-7ac7-11eb-875a-50ab9f28978d.png)
I don't know how easy/hard it would be to implement or how desired it is, but it's something that I know at least I would want, especially given that I make my own music and would love to play my own.

**Comment by aMytho** [comment]
I plan to add pretzel support to get the current song. It would be interesting to make a custom player though. The viewers could control the music playing...
Would you want it to be custom songs (on your PC), or just paste a youtube link? Playing songs on the streamers PC would be a lot easier and safer. I would have to improve security if I go the youtube route.
I'll look into it but it would be a ways off. I need to finish the core features first.

**Comment by aMytho** [comment]
Just looked into it, local songs would be very easy to add.

**Comment by Megami-Studios** [comment]
Well, I know I'd play my own songs via local.  YT and SC, as much as they would be nice, would be security minefields and chances are, if the artists are using SC repost, the music is probably going to Pretzel or Streambeats anyways.  So local is probably best.

**Comment by The-Dataminer** [comment]
What about Spotify integration? I'd love to be able to use either the web page or the app within Glimboi. This would reduce the amount of open programs or windows and contain everything nicely.

**Comment by aMytho** [comment]
It would reduce the amount of windows but it will still use the resources if the full player were to be included. I would have to connect to their API as I doubt their desktop app is open source.  I think I'll start with local and move on to third party apps after.

**Comment by aMytho** [comment]
Added local music player in 1.7.0

**Comment by Megami-Studios** [comment]
Working with it now.  I can see that it's going to need to remember the folder that's worked with, and the current song indicator may have to be stupid-proofed (mainly because I can foresee people saying, "Why can't I see the song title?" "Well, you need to set it up in OBS," "RGBA?  What's that?" and so on and so forth.)

May also want to put in the documentation as to what kinds of music tags it reads (ID3v1, APEv1, etc.)  Let me know if I can be of any help in that regard.

**Comment by aMytho** [comment]
If you want to help you are more than welcome to :) https://github.com/aMytho/GlimBoi-Docs is where we build the site. It uses hugo which takes markdown documents and converts them to a website. It would need to be installed along with the site to view the changes. The main changes would be adding a page for the music player, going over its basic functions and linking the overlay in OBS. Also need to tick the version number to 1.7.0

As for the folder name, I can try to have it remember. I want the bot to store as little data as possible but I can probably figure out something. We use https://www.npmjs.com/package/music-metadata for pulling metadata, should show what formats it supports there.

**Comment by Megami-Studios** [comment]
Okay, I'll see what I can do.  I've got my hands in a billion things at the moment, but if I can find the time, I'll throw in.  The project is worth it.

Additionally, took a look at the NPMJS page, and it looks like it supports the major metadata, so everyone should be covered.

Lastly, I did see that something might be disconnected.  I was testing out the music player, and whlie it works great, it's also showing that it's inactive.  Thought it was initially due to the installation (I hadn't rebooted), but did so again a couple of minutes ago and it's still showing the same thing.

![image](https://user-images.githubusercontent.com/2568634/117235132-25a30c00-adf4-11eb-82df-8a3984704877.png)

**Comment by aMytho** [comment]
The music icon is linked to the overlay, not the player. It starts when you press the button or if you connect to a chat. I should probably make that more clear. I want to mess with the UI around 1.8/1.9/2.0, probably get to it then.

**Comment by aMytho** [comment]
The bot now remembers the last folder played, as well as the volume. You will have to select a folder after updating, then it will automatically remember.

**Comment by aMytho** [comment]
This has been feature complete for a while so I'll close the issue.  If you want to see changes to it let me know.
