### ISSUE TITLE
Chat Timeouts

### ISSUE THREAD

**Issue by jessterli** [aMytho/GlimBoi#13]
I was looking to see how long the short time out was for Glimesh chat but I didn't see a way to untimeout myself or even how long those time outs are for. If still permitted for use in the future (as I really like the chat section) would it be possible to have a guide for the chat settings or the difference between the short and long time outs? Or a way to allow content creators and moderators to control the time outs at all?

**Comment by aMytho** [comment]
I will be writing a guide. Until then- short is 5 minutes, long is 15 minutes. The glimesh API does not yet support removing timeouts so that isn't an option yet. When they make that feature I will integrate it into the bot.
