### ISSUE TITLE
Increase size of draggable area

### ISSUE THREAD

**Issue by AdamHebby** [aMytho/GlimBoi#3]
At first I thought the draggable window area was in the very small control box like it is in most applications and really struggled to move it, then realized it was on the actual nav bar. Would probably save a lot of pain increasing this area or just moving it to the control box area / top of the window

https://i.gyazo.com/d7f0c7bf575a40ce226ca75b6b92cda8.mp4

https://i.gyazo.com/eb5132e221eb047ba58b17a7be5550f2.mp4

**Comment by aMytho** [comment]
Fixed in 1.8
