### ISSUE TITLE
Command panel data validation & formatting

### ISSUE THREAD

**Issue by AdamHebby** [aMytho/GlimBoi#6]
Numbers fields allows more than just numbers, none of them seem to have a max limit and if you enter too much data, it just overflows the box

![image](https://user-images.githubusercontent.com/18214951/109428697-28e2db80-79f0-11eb-8a3c-6a3b4b666531.png)

**Comment by aMytho** [comment]
If you add a space after a long word it will format. I don't know the exact word length limit but nobody would type something that long anyway. When you add a command it runs a formatter in the background, its supposed to tell the user what went wrong but the message is bugged. The command shouldn't be added if anything goes wrong. 

The launch day update will also add a filter for command data, ensuring that no hidden HTML was added. (If the source was copy/pasted.)
