### ISSUE TITLE
Feature: Web API integration 

### ISSUE THREAD

**Issue by JimmyMac3** [aMytho/GlimBoi#62]
Along the lines of the advice and dadjoke variables which I assume pull from an API / webpage somewhere out there on the internet could we get a variable that lets us put our own URL in and pull from it to display in chat. Example - https://scorpstuff.com/

**Comment by aMytho** [comment]
Scorpstuff is an awesome API. I use it for personal stuff all the time. I don't know if we can use it for Glimboi though. The terms say other bots can use it but I don't think they meant another bot that is distributed to many users (intended for personal use). 

I want to implement other API's. Allowing a URL fetch style variable would be very useful but I would need to work a little more on security. Currently the bot only communicates with Glimesh and two API services, this would require some catch statements to ensure no malicious code is ran. I will look into it though.

I'd also point out that if you can find a source of information you would like added to the bot (provided we can legally use it without any issues) we can download it to create a local API. This would remove the security problems. I want to keep most of them family friendly if possible.

**Comment by aMytho** [comment]
Completed in 1.8
