### ISSUE TITLE
Not Connecting at All

### ISSUE THREAD

**Issue by Megami-Studios** [aMytho/GlimBoi#7]
Not sure what the deal is, but I followed the instructions as per the page and am repeatedly getting this:
![image](https://user-images.githubusercontent.com/2568634/109453342-d15c6400-7a1f-11eb-9e5a-b5caddb9e96e.png)
At first I thought it was my firewall, but I checked and I had cleared it completely, so it's not that.  Any other ideas?

**Comment by aMytho** [comment]
I've been helping people with similar issues. 90% of the time its user error but I blame my bad instructions :) 
Anyway, I would ensure that the redirect URL is correct. It should be `http://localhost:3000/success`
Copy the *exact* URI into your dev app. It cannot be a https URL. 

If that doesn't work you need to ensure the server is running. After pressing authorize open a browser and head to `http://localhost:3000/auth`
If it redirects you to the glimesh auth page then it has to be something with your dev app.

**Comment by Megami-Studios** [comment]
Solved: all it took was a system reboot.  You may want to put that in the instructions.
(I know; seems so basic, and yet.... XD)

**Comment by aMytho** [comment]
Good to know, thanks for the info!

**Comment by aMytho** [comment]
Resolved
