### ISSUE TITLE
Users/Point Separation

### ISSUE THREAD

**Issue by aMytho** [aMytho/GlimBoi#79]
The users and points files are on the same file (chatbot). We need to separate them. I want to improve the point system a ton but I can't do that until they are separated. All the functions that use points would need to be adjusted to reflect this change.

**Comment by revthwack** [comment]
Is this still a valid & unaddressed issue?

**Comment by MythoAway** [comment]
It is still something that needs done. I'm not sure the best way to go about it. I'd prefer to keep the users and points on the same db if possible. It's just nice to have each file with 1 responsibility.

Ideally we would have a bunch of point specific functions later. A sort of "currency report" that the streamer can look at to see who has x amount of currency across the bot.

**Comment by aMytho** [comment]
We created a point leaderboard and custom page for currency settings. Since the changes were (partially) added and glimesh is ending, this issue will be closed.
