### ISSUE TITLE
Feature Requests for Raffle

### ISSUE THREAD

**Issue by royaltongue** [aMytho/GlimBoi#82]
Could the following features be added to the Raffle event?

1) Ability to raffle off points
2) Ability to set points amount (per Raffle (!raffle {amount} in chat))
3) Ability to change duration (permanently)

**Comment by aMytho** [comment]
1. As in have a requirement to spend x amount of points to enter? ex. you can only join a raffle if you have 500 points to spend on it? Can probably be adjusted to fit this. I think I'll have it be 0 unless changed though.
2. If 1 gets completed this would be possible.
3. Yeah, this can be done as well. Its actually in place for some events, I just never added the option to change it.

Currently working on the mod dashboard, but I can probably fit this in after that. I don't have an ETA yet, but hopefully I'll finish it soon. Thanks for the suggestion :)

**Comment by royaltongue** [comment]
I meant 1) as in "enter this raffle to win x points when it ends"

Also thanks for replying so quickly!

**Comment by aMytho** [comment]
Ah, ok. I could probably do that. Maybe I'll make different types of raffles then. Different rewards, and restrictions (ie sub only, followers, etc).

If you are looking for a gamble type game to earn/lose points !glimrealm is your friend :)

**Comment by aMytho** [comment]
Instead of changing the raffle, I'm thinking of creating a new game to do what you requested. I'll still add the ability to change the duration of the events, but a new game for that would be good. Actually have 3/4 new chat games coming.

**Comment by aMytho** [comment]
Added in 1.9.2
