### ISSUE TITLE
Feature: Add a list of recently connected chats and auto join a set chat.

### ISSUE THREAD

**Issue by aMytho** [aMytho/GlimBoi#9]
A lot of people have been wanting this feature. I think it can be done using cookies or web storage for keeping the channels. If anyone wants to work on this self assign the issue and let me know if you need any help.

**Comment by AdamHebby** [comment]
Im gonna attempt to do this

**Comment by AdamHebby** [comment]
If anyone is wondering, I have been working on this since my last comment (like 10 hours total), I'm making really good progress and I think I'm on the final stretch :D 

I should have a demo pretty soon and a PR by tomorrow

**Comment by aMytho** [comment]
Awesome 👍
