### ISSUE TITLE
Glimrealm Addidtions

### ISSUE THREAD

**Issue by MythoAway** [aMytho/GlimBoi#97]
https://github.com/aMytho/GlimBoi/blob/3cdfab04b923dca9f1ff45836b80f7fd87eca37c/lib/modules/events/glimRealm.ts#L109
We should add more Glimrop possibilities. We currently have about 30. There are a few new glimdrops we could reference.

**Comment by aMytho** [comment]
Ahhh, glimrealm! Fun game.

Closed due to Glimesh ending
